use_frameworks!

platform :ios, '10.0'

target 'ChatModule_Example' do
  pod 'FirebaseCore'
  pod 'Firebase/Auth', '~> 9.2.0'
  pod 'ChatModule', :path => '../'

  target 'ChatModule_Tests' do
    inherit! :search_paths

    
  end
end
